export type Language = 'en' | 'it';

export const translations = {
  en: {
    // Header
    documentation: 'Documentation',
    selectSong: 'Select a song...',
    
    // Cards
    inputSource: 'INPUT SOURCE',
    outputPreview: 'OUTPUT PREVIEW',
    sampleRate: 'Sample Rate',
    channels: 'Channels',
    mono: 'Mono',
    stereo: 'Stereo',
    
    // Center panel
    original: 'ORIGINAL',
    currentStep: 'CURRENT STEP',
    originalToggle: 'Original',
    processedToggle: 'Processed',
    whatHappened: 'What happened in this step',
    
    // Pipeline
    processingPipeline: 'PROCESSING PIPELINE',
    source: 'Source',
    filter: 'Filter',
    transformation: 'Transformation',
    upscaling: 'Upscaling',
    profiling: 'Profiling',
    separation: 'Separation',
    final: 'Final',
    
    // Status
    pending: 'Pending...',
    ready: 'Ready',
    noProcessing: 'No processing applied',
    processing: 'Processing...',
    complete: 'Complete',
    
    // Radar axes
    hiFreqExt: 'Hi-Freq Ext',
    stereoAxis: 'Stereo',
    loudness: 'Loudness',
    hfContrast: 'HF Contrast',
    
    // Step descriptions
    stepDescriptions: {
      'musicgen': 'This is the raw input audio generated by MusicGen AI model.',
      'precond': 'We clean up the input so the next models work better: remove artifacts, balance levels, and prepare the signal.',
      'apollo': 'We reshape the sound to improve clarity and texture—bringing out details without changing the vibe.',
      'audiosr': 'We increase audio resolution so it sounds more detailed and less \'compressed\'.',
      'maest': 'We analyze the track to understand its tonal balance and dynamics, so later steps can be more consistent.',
      'stereoize': 'We turn a narrow or mono sound into a wider stereo image, placing elements across left and right.',
      'master': 'We apply final polish: loudness, EQ balance, and limiting so it feels finished and consistent.',
    },
    
    // Errors
    loadError: 'Failed to load song data',
    
    // Legend
    legend: 'Legend',
    clickToToggle: 'Click to toggle visibility',
    
    // Disclaimer
    disclaimer: 'This tool is a demonstration that emulates real-time transformation by replaying pre-generated files produced by actual transformation runs',
    
    // Headphones hint
    headphonesHint: 'Use headphones for the best experience',
    
    // Pipeline hints
    pipelineHint: 'Click any step to hear the result',
    selectTrackPrompt: 'Select a track from above to start',
  },
  it: {
    // Header
    documentation: 'Documentazione',
    selectSong: 'Seleziona una canzone...',
    
    // Cards
    inputSource: 'SORGENTE INPUT',
    outputPreview: 'ANTEPRIMA OUTPUT',
    sampleRate: 'Frequenza',
    channels: 'Canali',
    mono: 'Mono',
    stereo: 'Stereo',
    
    // Center panel
    original: 'ORIGINALE',
    currentStep: 'STEP CORRENTE',
    originalToggle: 'Originale',
    processedToggle: 'Processato',
    whatHappened: 'Cosa è successo in questo step',
    
    // Pipeline
    processingPipeline: 'PIPELINE DI ELABORAZIONE',
    source: 'Sorgente',
    filter: 'Filtro',
    transformation: 'Trasformazione',
    upscaling: 'Upscaling',
    profiling: 'Profilazione',
    separation: 'Separazione',
    final: 'Finale',
    
    // Status
    pending: 'In attesa...',
    ready: 'Pronto',
    noProcessing: 'Nessuna elaborazione applicata',
    processing: 'Elaborazione...',
    complete: 'Completato',
    
    // Radar axes
    hiFreqExt: 'Est. Hi-Freq',
    stereoAxis: 'Stereo',
    loudness: 'Volume',
    hfContrast: 'Contrasto HF',
    
    // Step descriptions
    stepDescriptions: {
      'musicgen': 'Questo è l\'audio grezzo generato dal modello AI MusicGen.',
      'precond': 'Puliamo l\'input per far funzionare meglio i modelli successivi: rimuoviamo artefatti, bilanciamo i livelli e prepariamo il segnale.',
      'apollo': 'Rimodelliamo il suono per migliorare chiarezza e texture—evidenziando i dettagli senza cambiare l\'atmosfera.',
      'audiosr': 'Aumentiamo la risoluzione audio così suona più dettagliato e meno \'compresso\'.',
      'maest': 'Analizziamo la traccia per capire il suo bilanciamento tonale e la dinamica, così gli step successivi possono essere più coerenti.',
      'stereoize': 'Trasformiamo un suono stretto o mono in un\'immagine stereo più ampia, posizionando gli elementi tra sinistra e destra.',
      'master': 'Applichiamo la rifinitura finale: volume, bilanciamento EQ e limiting così suona finito e coerente.',
    },
    
    // Errors
    loadError: 'Impossibile caricare i dati della canzone',
    
    // Legend
    legend: 'Legenda',
    clickToToggle: 'Clicca per attivare/disattivare',
    
    // Disclaimer
    disclaimer: 'Questo strumento è una dimostrazione che emula la trasformazione in tempo reale riproducendo file pre-generati prodotti da esecuzioni di trasformazione reali',
    
    // Headphones hint
    headphonesHint: 'Usa le cuffie per una migliore esperienza',
    
    // Pipeline hints
    pipelineHint: 'Clicca su uno step per ascoltarne il risultato',
    selectTrackPrompt: 'Seleziona una traccia sopra per iniziare',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(lang: Language, key: TranslationKey): string {
  return translations[lang][key] as string;
}

export function getStepDescription(lang: Language, stepKey: string): string {
  const descriptions = translations[lang].stepDescriptions as Record<string, string>;
  return descriptions[stepKey] || descriptions['musicgen'];
}
